-- Generated by Babelfish script, do not add strings manually, only translate existing strings.
-- This is the base locale; values can be "true" so they default to their key, or any string to override that behaviour.
local L = LibStub("AceLocale-3.0"):NewLocale("MeeyrasLockouts", "enUS", true)


L["Alt-Click:"] = true
L["Alt-Right Click:"] = true
L["Click:"] = true
L["Command Line"] = true
L["ID"] = true
L["List lockouts in chat window."] = true
L["List lockouts in party or raid chat."] = true
L["Lockouts"] = true
L["Meeyra's Lockout Tracker"] = true
L["Name"] = true
L["No current lockouts"] = true
L["Open addon preferences."] = true
L["Print lockouts in party or raid chat."] = true
L["Profiles"] = true
L["Remaining"] = true
L["Show Minimap Icon"] = true
L["Toggle display of minimap button"] = true
L["Toggle visibility of minimap icon."] = true
L["Whether or not to show an icon on the minimap in addition or instead of using an LDB display"] = true
L["Expired"] = true
